# Generated by Django 6.0.3 on 2026-03-18 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QueryHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query_text", models.TextField(help_text="The original query text")),
                (
                    "intent",
                    models.CharField(
                        default="pending",
                        help_text="Detected query intent (rag, database, hybrid, smart)",
                        max_length=50,
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        blank=True, help_text="Generated answer text", null=True
                    ),
                ),
                (
                    "sources_json",
                    models.JSONField(
                        default=list, help_text="Source documents as JSON"
                    ),
                ),
                (
                    "metadata_json",
                    models.JSONField(default=dict, help_text="Query metadata as JSON"),
                ),
                (
                    "execution_time",
                    models.FloatField(
                        blank=True, help_text="Execution time in seconds", null=True
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=False, help_text="Whether query succeeded"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Session identifier for grouping queries",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Query History",
                "verbose_name_plural": "Query Histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["intent"], name="core_queryh_intent_9d3ad7_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="core_queryh_created_273df8_idx"
                    ),
                    models.Index(
                        fields=["success"], name="core_queryh_success_5305be_idx"
                    ),
                ],
            },
        ),
    ]
